/* Auto-generated by scripts/gen_key_points.py (v2 面试导向版)
 * 知识点标准：面试和实际工作中会重点考察的内容
 * text: 用一句话说清核心内容
 * keyword: 文章中实际存在的文字，确保能跳转
 */
window.KEY_POINTS = {
  // A. 深度学习入门介绍
  "llm-a-deep-learning": [
    { text: "模型=数学公式（参数a,b）；推理=用参数计算输出；训练=从数据反推参数（拟合）", keyword: "模型的推理过程" },
    { text: "四种训练范式：预训练→微调→人类对齐→强化微调，面试必考", keyword: "训练范式" },
    { text: "Base模型 vs Chat模型：未对齐vs已对齐，选模型的第一判断", keyword: "base模型" },
    { text: "Embedding：将离散文字转为高维连续向量，NLP基石概念", keyword: "嵌入（embedding）" },
    { text: "自回归生成：token化→embedding→概率化→采样→递归直到EOS", keyword: "自回归" },
    { text: "Forward前向计算+Backward反向求导=训练的核心机制", keyword: "forward和backward过程" },
    { text: "训练循环：DataLoader→forward→loss→backward→optimizer.step→zero_grad", keyword: "PyTorch基本训练代码范例" }
  ],
  // B. 魔搭社区和LLM大模型基础知识
  "llm-b-llm-basics": [
    { text: "LLM生态全景：基础模型→定制范式→多模态→Agent，高频面试概览", keyword: "基础模型研究" },
    { text: "多模态模型：文本+图像+音频统一处理，当前主流方向", keyword: "多模态模型" },
    { text: "模型微调：用少量标注数据将通用能力适配到具体任务", keyword: "模型微调" },
    { text: "Base模型=预训练未对齐，Chat模型=对齐后可对话，选型第一步", keyword: "Base模型和Chat模型" },
    { text: "模型推理：输入→tokenize→forward→采样→输出文本的完整链路", keyword: "模型推理" },
    { text: "RAG=检索增强生成：外挂知识库弥补模型知识缺陷", keyword: "LLM+RAG" }
  ],
  // C. 提示词工程 Prompt Engineering
  "llm-c-prompt-engineering": [
    { text: "Prompt四要素：指令+上下文+输入+输出格式，缺一不可", keyword: "指令" },
    { text: "Few-shot：提供少量示例让模型学习任务模式，高频实用技巧", keyword: "少样本学习" },
    { text: "善用分隔符：避免prompt注入，保证结构清晰", keyword: "善用分隔符" },
    { text: "思维链(CoT)：让模型逐步推理而非直接给答案，复杂任务必备", keyword: "思维链提示" },
    { text: "明确输出格式：JSON/表格/列表，减少后处理成本", keyword: "对输出格式的明确要求" }
  ],
  // D. Transformer 结构
  "llm-d-transformer": [
    { text: "RMSNorm：去掉均值只做缩放，比LayerNorm快且效果相当", keyword: "RMSNorm" },
    { text: "RoPE：旋转位置编码，通过复数旋转编码相对位置，面试高频", keyword: "RoPE" },
    { text: "SwiGLU：Swish激活+门控线性单元，现代LLM标配FFN结构", keyword: "SwiGLU" },
    { text: "GQA：分组查询注意力，KV头共享降显存，推理加速核心技术", keyword: "GQA" }
  ],
  // E. 技术选型
  "llm-e-tech-selection": [
    { text: "提示词工程 vs 微调 vs RAG vs Agent：四种方案的适用场景对比", keyword: "直接推理（提示词工程）" },
    { text: "RAG：知识密集型任务首选，可追溯、低成本、实时更新", keyword: "RAG" },
    { text: "Agent：复杂多步任务首选，能调用工具和API", keyword: "Agent" },
    { text: "模型选型：任务类型→模型规模→部署成本→响应延迟的决策链", keyword: "模型选型" }
  ],
  // F. 数据预处理
  "llm-f-data-preprocessing": [
    { text: "Tokenizer：BPE/WordPiece将文本切分为子词token，模型输入的第一步", keyword: "分词器（Tokenizer）" },
    { text: "Template：ChatML等对话模板定义system/user/assistant角色格式", keyword: "模板（Template）" },
    { text: "Loss=模型预测值与真实值的残差，交叉熵是分类任务标准loss", keyword: "交叉熵" }
  ],
  // G. 量化
  "llm-g-quantization": [
    { text: "量化=将FP32/FP16权重映射为INT8/INT4，显存降2-8倍", keyword: "量化是什么" },
    { text: "GPTQ：基于二阶信息的训练后量化，精度高但需校准数据", keyword: "AutoGPTQ" },
    { text: "BnB：HuggingFace集成的4/8bit量化，一行代码加载大模型", keyword: "Bitsandbytes" },
    { text: "GGML/GGUF：CPU推理格式，支持llama.cpp本地部署", keyword: "GGML" },
    { text: "AWQ：激活感知量化，保护重要通道不量化，推理更快", keyword: "AWQ" }
  ],
  // H. 训练
  "llm-h-training": [
    { text: "SFT用已标注数据将预训练知识涌现为特定任务能力", keyword: "已标注数据" },
    { text: "学习率：SFT通常1e-5~5e-5，过大则灾难性遗忘", keyword: "学习率" },
    { text: "LoRA：冻结原始权重W，只训练低秩矩阵A*B，显存降10倍", keyword: "LoRA" },
    { text: "数据集制作：instruction+input+output三字段格式，质量>数量", keyword: "数据集的制作" },
    { text: "训练框架选择：ms-swift/LLaMA-Factory/DeepSpeed按需选用", keyword: "训练框架选择" },
    { text: "LoRA还是全参：数据少用LoRA，数据多且充分用全参微调", keyword: "LoRA还是全参" }
  ],
  // I. LLM 和多模态模型高效推理实践
  "llm-i-inference": [
    { text: "推理加速：量化+KV Cache+多端部署是落地三板斧", keyword: "推理加速和多端推理" },
    { text: "幻觉问题：模型编造事实的本质原因和RAG缓解方案", keyword: "幻觉" },
    { text: "RAG vs Finetune：开卷考试vs专业课学习，按场景选方案", keyword: "RAG（开卷考试）VS." }
  ],
  // J. 部署
  "llm-j-deployment": [
    { text: "vLLM：PagedAttention+连续批处理，高吞吐推理引擎", keyword: "VLLM" },
    { text: "FastChat：快速搭建多模型服务的开源部署框架", keyword: "FastChat" },
    { text: "llama.cpp：纯CPU推理方案，GGUF格式支持端侧部署", keyword: "llama.cpp" },
    { text: "Temperature/Top-P/Top-K：控制生成多样性的三个关键超参", keyword: "重要推理超参数" },
    { text: "KVCache：缓存历史K/V矩阵避免重复计算，推理加速核心", keyword: "KVCache" }
  ],
  // K. 大模型自动评估理论和实战 LLM Automatic Evaluation
  "llm-k-evaluation": [
    { text: "LLM评估方法论：Rule-based vs Model-based，客观vs主观", keyword: "LLM评估的方法论" },
    { text: "Benchmark体系：MMLU/BBH/GSM8K等基准的设计思想", keyword: "基准和指标" },
    { text: "Generate模式：直接生成response评估开放能力", keyword: "Generate" },
    { text: "Likelihood模式：计算各选项对数似然概率做选择题", keyword: "Likelihood" }
  ],
  // L. LISA 微调技术解析
  "llm-l-lisa": [
    { text: "LISA：随机冻结中间层只训练少数层，LoRA之外的省显存方案", keyword: "技术解析" },
    { text: "Flash Attention+梯度检查点：省显存训练的标配组合", keyword: "flash_attn" },
    { text: "gradient_checkpointing：用时间换空间，显存可降50%+", keyword: "gradient_checkpointing" }
  ],
  // M. 人类偏好对齐训练
  "llm-m-alignment": [
    { text: "RLHF：训练奖励模型→PPO优化策略，经典但复杂的对齐方案", keyword: "RLHF" },
    { text: "DPO：跳过奖励模型直接用偏好对做优化，简单高效的替代方案", keyword: "DPO" },
    { text: "SimPO/ORPO/KTO：无需参考模型的新一代对齐算法，工程更简洁", keyword: "SimPO" },
    { text: "对齐三阶段：SFT→奖励建模→强化学习(RLHF)，面试必考流程", keyword: "第一阶段 SFT训练" },
    { text: "选RLHF还是DPO：数据量大+追求极致用RLHF，否则DPO更实用", keyword: "如何选择人类偏好对齐训练算法？" }
  ],
  // N. 量化技术解析
  "llm-n-quantization-deep": [
    { text: "量化原理：浮点映射到整数的数学过程，absmax/zeropoint两种方式", keyword: "量化的定义和基本原理" },
    { text: "BnB量化：nf4数据类型+双重反量化，QLoRA的核心技术", keyword: "BnB量化" },
    { text: "QLoRA：4bit量化+LoRA微调，单卡训练70B模型的关键技术", keyword: "QLoRA" },
    { text: "GPTQ：逐列量化+Hessian信息补偿误差，高精度离线量化", keyword: "GPTQ量化" },
    { text: "AWQ：保护1%重要权重通道不量化，精度损失最小化", keyword: "AWQ量化" }
  ],
  // O. ModelScope-Agent AgentFabric 微调最佳实践
  "llm-o-agent-fabric": [
    { text: "Agent数据格式：thought→action→observation的推理循环", keyword: "工具" },
    { text: "Agent微调数据准备：工具描述+调用示例+多轮对话", keyword: "数据准备" },
    { text: "微调流程：LoRA训练→合并权重→部署模型→接入AgentFabric", keyword: "微调流程" },
    { text: "模型部署：合并LoRA后通过vLLM/SWIFT拉起推理服务", keyword: "部署模型" }
  ],
  // P. PlayGround：训练一个古文翻译腔机器人
  "llm-p-playground": [
    { text: "端到端实战：数据收集→清洗→SFT训练→评估→部署全流程", keyword: "古文翻译腔" },
    { text: "数据制作：爬取平行语料并构造instruction-output对", keyword: "数据" },
    { text: "训练→推理→评估→部署的完整工程化链路实践", keyword: "推理和评估" }
  ],
  // Q. 从 OpenAI O1 看大模型的复杂推理能力
  "llm-q-reasoning": [
    { text: "O1推理范式：长思维链+自我验证+回溯纠错，推理能力质变", keyword: "O1" },
    { text: "复杂推理=规划+分解+验证，是LLM走向AGI的关键能力", keyword: "复杂推理" },
    { text: "Chain of Thought：让模型展示推理过程而非直接给答案", keyword: "Chain of Thought" }
  ],
  // S. PPO 和 GRPO
  "llm-s-ppo-grpo": [
    { text: "GRPO：组相对策略优化，无需critic模型，DeepSeek采用的方案", keyword: "GRPO" },
    { text: "PPO：近端策略优化，clip限制更新幅度防止训崩，RLHF核心算法", keyword: "近端策略优化" },
    { text: "重要性采样：用旧策略数据更新新策略，off-policy的数学基础", keyword: "重要性采样" }
  ],
  // 基于Transformers，diffusion技术解析+实战
  "aigc-transformers-diffusion": [
    { text: "视觉数据Patch化：图像/视频统一切patch输入Transformer", keyword: "视觉数据转化为Patch" },
    { text: "DiT：用Transformer替代U-Net做扩散模型，Sora核心架构", keyword: "DiT" },
    { text: "U-ViT：ViT骨架+长跳跃连接做扩散生成，CVPR2023", keyword: "U-ViT" },
    { text: "Latte：时空Transformer处理视频生成，时间+空间双attention", keyword: "Latte" }
  ],
  // 图像理解与生成统一模型——前沿模型架构理解
  "blog-articles-all2all-survey": [
    { text: "统一模型四大路线：纯AR/AR+Diff串联/AR+Diff并联/单模型混合", keyword: "纯自回归路线" },
    { text: "AR+Diffusion架构：LLM生成语义token→Diffusion解码为图像", keyword: "AR + Diffusion" },
    { text: "核心差异：图像如何编码、如何生成编码、如何解码", keyword: "不同路线方法在理解任务上的差别在于图像编码的方式" }
  ],
  // Agent Lightning：面向AI Agents的强化学习框架深度分析报告
  "blog-daily-agent-lightning": [
    { text: "Agent训练建模为MDP：状态/动作/奖励形式化Agent决策", keyword: "马尔可夫决策过程" },
    { text: "Agent执行与RL训练解耦：无需修改Agent代码即可训练", keyword: "RL训练的完全解耦" },
    { text: "三任务验证：Text-to-SQL/RAG/数学QA证明框架通用性", keyword: "Text-to-SQL" }
  ],
  // DINOv3: 通过自监督学习扩展视觉基础模型
  "blog-daily-dinov3": [
    { text: "DINOv3：70亿参数自监督视觉模型，通用视觉编码器", keyword: "DINOv3" },
    { text: "Gram锚定：解决SSL扩展时密集特征质量下降的核心创新", keyword: "Gram锚定" },
    { text: "知识蒸馏构建模型家族：大模型→多尺寸小模型适配不同场景", keyword: "知识蒸馏" }
  ],
  // OpenVINO 推理优化
  "nb-llm-openvino": [
    { text: "能用OpenVINO将模型转换为IR格式并在CPU/iGPU上高效推理", keyword: "OpenVINO" },
    { text: "能使用pipeline快速搭建文本生成/对话推理流水线", keyword: "pipeline" },
    { text: "INT8量化：进一步压缩模型提升CPU推理速度", keyword: "INT8" }
  ],
  // RAG + Rerank 实战
  "nb-llm-rag-llamaindex": [
    { text: "能配置embedding模型将文档向量化存入索引", keyword: "embedding" },
    { text: "Rerank二次排序：粗检索→精排序提升召回质量", keyword: "Rerank" },
    { text: "能用LlamaIndex构建完整的RAG检索增强生成流水线", keyword: "LlamaIndex" }
  ],
  // 多模态模型评估实战
  "nb-llm-vlmevalkit": [
    { text: "能用VLMEvalKit对多模态模型做标准化评估", keyword: "VLMEvalKit" },
    { text: "评估流程：部署模型→配置数据集→运行评测→查看报告", keyword: "多模态模型评估" }
  ],
  // Dify RAG+Agent 框架
  "nb-llm-dify": [
    { text: "能用Dify低代码平台快速搭建RAG+Agent应用", keyword: "十分钟速通Dify" }
  ],
  // LLaMA-Factory 微调实战
  "nb-llm-llama-factory": [
    { text: "能用LLaMA-Factory的YAML配置完成LoRA微调全流程", keyword: "LLaMA-Factory" }
  ],
  // llama.cpp 本地推理
  "nb-llm-llamacpp": [
    { text: "llama.cpp：C++实现的纯本地推理引擎，支持CPU/Metal加速", keyword: "llama.cpp" },
    { text: "GGUF格式：量化模型的标准格式，支持多种量化精度", keyword: "GGUF" },
    { text: "能下载GGUF模型并启动本地OpenAI兼容API服务", keyword: "启动本地服务器" }
  ],
  // Nexa SDK 端侧推理
  "nb-llm-nexa": [
    { text: "能用Nexa SDK在端侧设备运行模型推理", keyword: "Nexa SDK" },
    { text: "模型转换：将HuggingFace模型转为Nexa格式部署", keyword: "模型转换" },
    { text: "能启动本地服务器并通过API调用模型", keyword: "本地服务器部署与 API 调用" }
  ],
  // Unsloth 高效微调
  "nb-llm-unsloth": [
    { text: "Unsloth：比标准训练快2倍的高效微调框架", keyword: "快2倍" },
    { text: "完整流程：数据准备→训练→推理→保存→导出GGUF", keyword: "数据准备" },
    { text: "能将微调后模型导出为GGUF格式供本地部署", keyword: "GGUF" }
  ],
  // vLLM 推理加速实战
  "nb-llm-vllm": [
    { text: "能启动vLLM服务并通过OpenAI兼容API调用", keyword: "vLLM推理框架" },
    { text: "vLLM核心：PagedAttention管理KV Cache显存，大幅提升吞吐", keyword: "PagedAttention" },
    { text: "Continuous Batching：请求动态进出批次，GPU利用率最大化", keyword: "Continuous Batching" }
  ],
  // 知乎数据集全流程训练
  "nb-llm-zhihu-train": [
    { text: "LLM训练全链路：数据下载→清洗→训练→评估→上传的完整实践", keyword: "数据集准备" },
    { text: "能用data-juicer做数据清洗和质量过滤", keyword: "数据清洗" },
    { text: "能用ms-swift完成LoRA训练并导出合并后的模型", keyword: "使用ms-swift训练模型" },
    { text: "能用evalscope评估模型通用能力和自定义数据集效果", keyword: "使用evalscope评估模型" }
  ],
  // 10步快速训练入门
  "nb-llm-quick-train": [
    { text: "10步完成从数据加载到LoRA微调的最简训练流程", keyword: "swift" },
    { text: "能用ms-swift框架一键完成模型加载→训练→推理", keyword: "LoRA" }
  ],
  // 10分钟改变大模型自我认知
  "nb-llm-self-cognition": [
    { text: "自我认知微调：修改模型的身份回答，定制专属机器人", keyword: "自我认知" },
    { text: "支持命令行/Python/Web-UI三种训练方式", keyword: "命令行界面" },
    { text: "能通过Web-UI界面无代码完成微调和推理", keyword: "Web-UI" }
  ],
  // ViT 图像分类最佳实践
  "nb-aigc-vit-bestpractice": [
    { text: "ViT：将图像切分为patch序列后用Transformer做分类", keyword: "什么是ViT" }
  ],
  // ViViT 视频分类最佳实践
  "nb-aigc-vivit-bestpractice": [
    { text: "Tubelet Embedding：从视频中提取时空管状token", keyword: "Tubelet Embedding" },
    { text: "均匀帧采样：视频分类的标准预处理策略", keyword: "均匀帧采样" },
    { text: "空间-时间注意力：分别建模空间和时间维度的依赖关系", keyword: "空间-时间注意力机制" }
  ],
  // 图像Patch提取与可视化
  "nb-aigc-patch": [
    { text: "图像Patch化：将图像切分为固定大小的patch序列", keyword: "图像预处理" },
    { text: "Patch是ViT/DiT等视觉Transformer的基本输入单元", keyword: "创建Patch" }
  ],
  // 1.2 1.1 有监督和无监督学习的概念
  "adv-01-02-supervised-concept": [
    { text: "有监督=有标签学标签，无监督=无标签学结构，最基本的范式区分", keyword: "有监督学习" },
    { text: "目标函数=经验风险+正则项，统计学习的统一框架", keyword: "有监督学习的目标函数分解" },
    { text: "半监督+自监督：少标签场景的解法，预训练的理论基础", keyword: "半监督学习与自监督学习" },
    { text: "VC维：衡量模型容量的理论工具，泛化界的核心概念", keyword: "泛化界与 VC 维" },
    { text: "偏差-方差权衡：模型复杂度的核心矛盾，面试必考", keyword: "偏差-方差权衡" }
  ],
  // 1.3 1.2 数据集的概念和含义
  "adv-01-03-dataset": [
    { text: "i.i.d.假设：训练/测试同分布，机器学习的基本前提", keyword: "独立同分布假设" },
    { text: "交叉验证：小数据集上评估模型的标准方法", keyword: "交叉验证" },
    { text: "训练集/验证集/测试集：防止过拟合的数据划分三件套", keyword: "训练集、验证集与测试集" },
    { text: "类别不平衡：真实场景高频问题，需过采样/代价敏感学习", keyword: "类别不平衡" },
    { text: "维度灾难：高维空间数据稀疏导致模型失效", keyword: "维度灾难" }
  ],
  // 1.4 1.3 机器学习、深度学习、强化学习
  "adv-01-04-ml-dl-rl": [
    { text: "ML⊃DL⊃LLM：机器学习是大类，深度学习是子集，大模型是应用", keyword: "机器学习" },
    { text: "强化学习：Agent在环境中试错，最大化累积奖励", keyword: "强化学习" },
    { text: "深度学习=自动特征提取(表示学习)，无需手工特征工程", keyword: "表示学习" },
    { text: "MDP：状态→动作→奖励→新状态，强化学习的数学框架", keyword: "马尔可夫决策过程" },
    { text: "RLHF=深度学习+强化学习融合，大模型对齐的核心技术", keyword: "价值函数与贝尔曼方程" }
  ],
  // 1.5 1.4 回归、分类与聚类
  "adv-01-05-regression-clustering": [
    { text: "回归=预测连续值，分类=预测离散类别，聚类=无标签分组", keyword: "回归" },
    { text: "线性回归：最简单的模型，MSE损失+正规方程/梯度下降求解", keyword: "线性回归" },
    { text: "交叉熵损失：分类任务标准损失函数，面试手推必考", keyword: "交叉熵损失" },
    { text: "聚类算法：K-means/层次聚类/DBSCAN，无监督的核心应用", keyword: "聚类算法" }
  ],
  // 2.3 2.2 最小二乘法基础
  "adv-02-03-least-squares": [
    { text: "最小二乘法：最小化残差平方和，回归的经典求解方法", keyword: "最小二乘法" },
    { text: "几何解释：回归=在列空间找最近投影点", keyword: "几何解释" },
    { text: "正规方程：X^T*X*w=X^T*y，闭式解的条件和局限", keyword: "正规方程" }
  ],
  // 2.4 2.3 过拟合与欠拟合
  "adv-02-04-overfit-underfit": [
    { text: "过拟合=训练好测试差，欠拟合=两者都差，面试必问", keyword: "过拟合" },
    { text: "模型复杂度：参数越多越容易过拟合，需正则化约束", keyword: "模型复杂度" },
    { text: "正则化：L1稀疏/L2平滑/Dropout随机失活，防过拟合三板斧", keyword: "正则化" }
  ],
  // 2.5 2.4 泛化性
  "adv-02-05-generalization": [
    { text: "泛化=模型在未见数据上的表现，ML的终极目标", keyword: "泛化性" },
    { text: "泛化误差=训练误差+泛化gap，gap越小模型越好", keyword: "泛化误差" },
    { text: "VC维：衡量假设空间复杂度，维度越高需要越多数据", keyword: "VC 维" },
    { text: "样本复杂度：达到给定泛化精度所需的最少训练样本数", keyword: "样本复杂度" }
  ],
  // 2.6 2.5 损失函数与正则化
  "adv-02-06-loss-regularization": [
    { text: "损失函数：衡量预测与真实的差距，MSE/CE/Huber按任务选", keyword: "损失函数" },
    { text: "Huber损失：MSE+MAE结合，对异常值鲁棒", keyword: "Huber 损失" },
    { text: "交叉熵损失：-Σy*log(ŷ)，分类任务的标准选择", keyword: "交叉熵损失" },
    { text: "L2正则化：权重衰减，防止参数过大导致过拟合", keyword: "L2 正则化" },
    { text: "L1正则化：产生稀疏解，可做特征选择", keyword: "L1 正则化" }
  ],
  // 2.7 2.6 梯度下降法与优化器
  "adv-02-07-gradient-descent": [
    { text: "梯度下降：沿loss最陡下降方向更新参数，优化的基本方法", keyword: "梯度下降" },
    { text: "学习率：步长太大震荡不收敛，太小收敛慢，最关键的超参", keyword: "学习率" },
    { text: "SGD+动量：积累历史梯度方向加速收敛，减少震荡", keyword: "SGD" },
    { text: "SGD→Momentum→Adam：优化器演进，Adam是当前默认选择", keyword: "Adam" }
  ],
  // 3.5 3.4 Transformer 架构：编码器与解码器
  "adv-03-05-transformer": [
    { text: "Transformer抛弃循环结构，纯注意力机制建模序列依赖", keyword: "从 Seq2Seq 到 Transformer" },
    { text: "自注意力：Q*K^T/√d→softmax→*V，序列内部信息交互", keyword: "自注意力" },
    { text: "多头机制：多组QKV并行关注不同子空间的信息", keyword: "多头" },
    { text: "FFN=两层线性+激活，提供逐位置的非线性变换", keyword: "前馈网络" },
    { text: "残差连接+层归一化：深层网络训练的两个必备组件", keyword: "残差连接" },
    { text: "Decoder-only：GPT系列架构，因果掩码实现自回归生成", keyword: "Decoder-only" }
  ],
  // 3.6 3.5 分词与词典向量化
  "adv-03-06-tokenization": [
    { text: "词表大小：太小OOV多，太大embedding参数爆炸，需权衡", keyword: "词表" },
    { text: "BPE：字节对编码，从字符出发合并高频对，GPT系列标配", keyword: "BPE" },
    { text: "WordPiece：似然驱动的分词，BERT采用的方法", keyword: "WordPiece" },
    { text: "Unigram：概率模型+剪枝，支持多种分词结果", keyword: "Unigram" }
  ],
  // 3.7 3.6 Embedding 与权重共享
  "adv-03-07-embedding": [
    { text: "Embedding：查表操作，将离散token映射为稠密向量", keyword: "Embedding" },
    { text: "权重共享：输入embedding和输出分类头共享，减少参数量", keyword: "权重共享" },
    { text: "Word2Vec：Skip-gram/CBOW学习词向量，理解相似度的基础", keyword: "Word2Vec" }
  ],
  // 3.8 3.7 位置编码
  "adv-03-08-positional-encoding": [
    { text: "正弦位置编码：sin/cos函数编码绝对位置，原始Transformer方案", keyword: "正弦位置编码" },
    { text: "RoPE：旋转位置编码，内积自然包含相对位置，LLaMA/Qwen标配", keyword: "RoPE" },
    { text: "ALiBi：注意力线性偏置，无需训练即可外推到更长序列", keyword: "ALiBi" }
  ],
  // 3.9 3.8 激活函数：从 Softmax 到 SwiGLU
  "adv-03-09-activation": [
    { text: "Softmax：归一化为概率分布，注意力权重和输出层必用", keyword: "Softmax" },
    { text: "SwiGLU：Swish激活+门控机制，LLaMA/Qwen的FFN标配", keyword: "SwiGLU" },
    { text: "ReLU：max(0,x)，简单高效但有dying neuron问题", keyword: "ReLU" },
    { text: "GELU：高斯误差线性单元，BERT/GPT标配激活函数", keyword: "GELU" }
  ],
  // 3.10 3.9 正则化与残差连接
  "adv-03-10-regularization-residual": [
    { text: "残差连接：x+F(x)跳跃连接，解决深层网络梯度消失", keyword: "残差连接" },
    { text: "LayerNorm vs RMSNorm：RMSNorm去掉均值更快，现代LLM首选", keyword: "RMSNorm" },
    { text: "Pre-Norm vs Post-Norm：Pre-Norm训练更稳定，大模型标配", keyword: "Pre-Norm" },
    { text: "权重衰减(AdamW)：解耦的L2正则，现代训练标配", keyword: "权重衰减" },
    { text: "梯度裁剪：限制梯度范数防止爆炸，大模型训练必备", keyword: "梯度裁剪" }
  ],
  // 3.11 3.10 注意力机制
  "adv-03-11-attention": [
    { text: "多头注意力：并行多组QKV捕获不同子空间特征", keyword: "多头注意力" },
    { text: "MHA→MQA→GQA：KV头共享演进，平衡质量和推理速度", keyword: "分组查询注意力" },
    { text: "缩放点积注意力：Q*K^T/√d_k→softmax→V，面试手推必考", keyword: "缩放点积注意力" },
    { text: "因果掩码：下三角mask保证自回归，只看过去不看未来", keyword: "因果掩码" },
    { text: "Flash Attention：IO感知的分块计算，不改结果但快2-4倍", keyword: "Flash Attention" }
  ],
  // 3.12 3.11 MoE 稀疏网络
  "adv-03-12-moe": [
    { text: "MoE：每个token只激活Top-K个专家，总参数大但计算少", keyword: "稀疏激活" },
    { text: "门控机制：Router决定token分配给哪些专家，核心设计点", keyword: "门控机制" },
    { text: "负载均衡：辅助损失防止token都涌向少数专家", keyword: "负载均衡" },
    { text: "Switch Transformer：Top-1路由，极致稀疏的MoE方案", keyword: "Switch Transformer" },
    { text: "DeepSeek MoE：共享专家+细粒度专家的高效设计", keyword: "DeepSeek" }
  ],
  // 3.13 3.12 多模态与全模态模型
  "adv-03-13-multimodal": [
    { text: "多模态融合：早期/晚期/交叉注意力三种策略的优劣权衡", keyword: "多模态" },
    { text: "CLIP：对比学习对齐图文embedding，多模态基础模型", keyword: "CLIP" },
    { text: "LLaVA：视觉编码器+MLP适配器+LLM的主流VLM架构", keyword: "LLaVA" },
    { text: "视觉Tokenizer：连续图像→离散token，统一多模态的关键", keyword: "视觉 Tokenizer" },
    { text: "VQ-VAE：将图像离散化为token，使AR生成图像成为可能", keyword: "VQ-VAE" }
  ],
  // 4.2 4.1 VAE：变分自编码器
  "adv-04-02-vae": [
    { text: "VAE：编码器映射到高斯分布→采样→解码器重建，生成模型基础", keyword: "变分自编码器" },
    { text: "ELBO=重建损失+KL散度，VAE优化的数学目标", keyword: "ELBO" },
    { text: "重参数化技巧：z=μ+σ*ε使采样可导，面试常问", keyword: "重参数化技巧" },
    { text: "VQ-VAE：离散潜空间替代连续高斯，图像tokenizer的基础", keyword: "VQ-VAE" },
    { text: "Latent Diffusion：先VAE压缩到潜空间再做扩散，SD核心架构", keyword: "Latent Diffusion" }
  ],
  // 4.3 4.2 GAN：生成对抗网络
  "adv-04-03-gan": [
    { text: "GAN：生成器G和判别器D对抗博弈，minmax优化", keyword: "生成对抗网络" },
    { text: "判别器和生成器的平衡训练是GAN成功的关键", keyword: "判别器" },
    { text: "模式坍缩：G只生成少数样本骗过D，GAN核心难题", keyword: "模式坍缩" },
    { text: "WGAN：用Wasserstein距离替代JS散度，训练更稳定", keyword: "WGAN" }
  ],
  // 4.4 4.3 去噪概率模型
  "adv-04-04-ddpm": [
    { text: "DDPM数学：q(x_t|x_0)闭式采样，p(x_{t-1}|x_t)神经网络参数化", keyword: "DDPM" },
    { text: "DDPM：前向逐步加噪→逆向逐步去噪，扩散模型核心原理", keyword: "前向过程" },
    { text: "去噪过程：从纯噪声逐步还原图像，每步预测噪声ε", keyword: "去噪过程" },
    { text: "噪声调度：β序列控制加噪速度，线性/余弦策略影响生成质量", keyword: "噪声调度" }
  ],
  // 4.5 4.4 扩散模型结构
  "adv-04-05-diffusion-arch": [
    { text: "U-Net：编码器-解码器+跳跃连接，经典扩散模型骨架", keyword: "U-Net" },
    { text: "DiT：Transformer替代U-Net，scalable的扩散架构", keyword: "DiT" },
    { text: "交叉注意力：注入文本条件信息，实现文生图的关键模块", keyword: "交叉注意力" }
  ],
  // 4.6 4.5 常用技术
  "adv-04-06-common-tech": [
    { text: "CFG：无分类器引导，用有/无条件预测差值增强条件控制", keyword: "Classifier-Free Guidance" },
    { text: "ControlNet：额外分支注入边缘/深度等空间条件控制生成", keyword: "ControlNet" },
    { text: "条件生成：文本/图像/结构等多种条件引导生成结果", keyword: "条件生成" },
    { text: "IP-Adapter：解耦图像prompt和文本prompt的条件注入方法", keyword: "IP-Adapter" }
  ],
  // 5.2 5.1 策略梯度与价值函数
  "adv-05-02-policy-value": [
    { text: "策略梯度定理：∇J=E[∇logπ*R]，RL优化的数学基础", keyword: "策略梯度定理" },
    { text: "REINFORCE：蒙特卡洛采样估计策略梯度，最基础的PG算法", keyword: "REINFORCE" },
    { text: "基线trick：减去基线降低方差但不改变梯度期望", keyword: "基线" },
    { text: "优势函数A=Q-V：衡量动作相对平均水平的好坏程度", keyword: "优势函数" },
    { text: "Actor-Critic：Actor选动作+Critic评估价值，降低方差", keyword: "Actor-Critic" }
  ],
  // 5.3 5.2 广义优势估计
  "adv-05-03-gae": [
    { text: "GAE：广义优势估计，用λ参数平衡偏差和方差", keyword: "广义优势估计" },
    { text: "TD(λ)：多步TD的指数加权，λ=0纯TD/λ=1蒙特卡洛", keyword: "GAE" },
    { text: "折扣因子γ：衡量未来奖励的当前价值，γ越小越短视", keyword: "折扣因子" }
  ],
  // 5.4 5.3 Value-Based 与 Policy-Based 算法
  "adv-05-04-value-based-policy-based": [
    { text: "Value-Based(DQN)：学Q值选最优动作，离散动作空间适用", keyword: "Value-Based" },
    { text: "Policy-Based(PPO)：直接优化策略，连续动作空间适用", keyword: "Policy-Based" },
    { text: "Q-Learning：off-policy TD，用max Q更新，DQN的理论基础", keyword: "Q-Learning" },
    { text: "DQN：深度网络拟合Q函数+经验回放+目标网络", keyword: "DQN" }
  ],
  // 5.5 5.4 Off-Policy 优化
  "adv-05-05-off-policy": [
    { text: "Off-Policy：用历史数据更新当前策略，样本效率高", keyword: "Off-Policy" },
    { text: "经验回放：存储历史transition打破时序相关性", keyword: "经验回放" },
    { text: "重要性采样：校正行为策略和目标策略的分布差异", keyword: "重要性采样" }
  ],
  // 6.2 6.1 Prefill 与 Decode
  "adv-06-02-prefill-decode": [
    { text: "Prefill：一次性处理全部输入token，计算密集型", keyword: "Prefill" },
    { text: "Decode：逐token自回归生成，访存密集型（memory-bound）", keyword: "Decode" },
    { text: "TTFT(Time to First Token)：首token延迟，用户体验关键指标", keyword: "TTFT" }
  ],
  // 6.3 6.2 KV Cache
  "adv-06-03-kvcache": [
    { text: "KV Cache：缓存历史K/V避免重复计算，推理加速核心技术", keyword: "KV Cache" },
    { text: "显存占用=2*n_layers*seq_len*d_model*2bytes，长序列的瓶颈", keyword: "注意力计算回顾" },
    { text: "KV Cache思想：前面token的K/V不变，只计算新token的QKV", keyword: "KV Cache 的思想" }
  ],
  // 6.4 6.3 解码策略
  "adv-06-04-decoding-strategy": [
    { text: "解码策略：贪婪/Top-k/Top-p/温度采样控制生成多样性", keyword: "解码策略" },
    { text: "贪婪解码：每步选概率最高token，确定性但单调", keyword: "贪婪" },
    { text: "Top-k/Top-p：截断低概率token再采样，平衡质量和多样性", keyword: "Top-k" },
    { text: "Temperature：logits/T调节分布尖锐度，T→0趋近贪婪", keyword: "temperature" }
  ],
  // 6.5 6.4 Paged Attention
  "adv-06-05-pagedattention": [
    { text: "Paged Attention：借鉴虚拟内存，按页管理KV Cache显存", keyword: "Paged Attention" },
    { text: "解决内存碎片：逻辑块→物理块映射消除显存浪费", keyword: "内存碎片" },
    { text: "逻辑块/物理块：KV按固定大小分块，动态分配物理显存", keyword: "逻辑块" }
  ],
  // 6.6 6.5 Continuous Batching
  "adv-06-06-continuousbatching": [
    { text: "Continuous Batching：请求动态进出批次，GPU利用率最大化", keyword: "Continuous Batching" },
    { text: "静态批处理的问题：短请求等长请求，GPU严重空闲浪费", keyword: "静态批处理" },
    { text: "吞吐量提升：批次始终满载运行，相比静态提升数倍", keyword: "吞吐量" }
  ],
  // 11.2 Prompt Engineering
  "adv-11-02-prompt-engineering": [
    { text: "Prompt结构：系统设定+上下文+任务指令+输入+输出格式+示例", keyword: "提示词的基本结构" },
    { text: "系统提示词：定义模型角色和行为准则的全局设定", keyword: "系统提示词" },
    { text: "Chain-of-Thought：让模型逐步推理，复杂数学/逻辑必备", keyword: "Chain-of-Thought" },
    { text: "CoT：思维链提示的缩写，加一句'让我们一步步思考'即可", keyword: "CoT" },
    { text: "Zero-shot vs Few-shot：无示例直接做 vs 给几个例子模仿", keyword: "Zero-shot Prompting" }
  ],
  // 11.3 数据集格式与训练阶段
  "adv-11-03-dataset-stage": [
    { text: "数据质量>数量：高质量少量数据效果优于低质量大量数据", keyword: "数据集格式" },
    { text: "训练三阶段：预训练(海量文本)→SFT(指令数据)→RLHF(偏好数据)", keyword: "训练阶段" },
    { text: "预训练数据：万亿token级别的无标注文本语料", keyword: "预训练" },
    { text: "SFT数据格式：Alpaca/ChatML/ShareGPT三种主流格式", keyword: "SFT" },
    { text: "RLHF数据：chosen/rejected偏好对，训练奖励模型", keyword: "RLHF" }
  ],
  // 11.4 训练中的问题
  "adv-11-04-training-issues": [
    { text: "灾难性遗忘：微调后通用能力下降，PEFT/数据混合/EWC缓解", keyword: "灾难性遗忘" },
    { text: "数值溢出：FP16下exp/softmax易overflow，BF16/混合精度解决", keyword: "数值溢出" },
    { text: "梯度爆炸：loss突然NaN，梯度裁剪+学习率衰减是标配", keyword: "梯度爆炸" },
    { text: "MFU(Model FLOPs Utilization)：GPU算力实际利用率，优化指标", keyword: "MFU" }
  ],
  // 13.1 智能体技术
  "adv-13-01-intro": [
    { text: "智能体=LLM+工具+记忆+规划，从模型到Agent的进化", keyword: "核心要素" },
    { text: "从LLM到Agent：理解意图→自主规划→调用工具→灵活调整", keyword: "LLM到Agent" }
  ],
  // 13.2 智能体发展历史
  "adv-13-02-agent-history": [
    { text: "Agent演进：符号主义→行为主义→深度RL→LLM驱动四个时代", keyword: "符号主义" },
    { text: "多智能体协作：AutoGen/MetaGPT等框架实现分工协作", keyword: "多智能体" },
    { text: "ReACT：思考-行动-观察循环，当前主流Agent框架的基础", keyword: "ReACT" },
    { text: "Agentic Workflow：Agent工作流编排是当前落地的主要形态", keyword: "Agentic Workflow" }
  ],
  // 13.3 代码平台与低代码平台
  "adv-13-03-low-code-platform": [
    { text: "低代码平台：可视化拖拽编排，快速原型和非技术人员友好", keyword: "低代码平台" },
    { text: "代码优先(LangChain)vs低代码(Dify)：灵活性vs开发速度的权衡", keyword: "代码优先平台" },
    { text: "混合架构：代码定义核心逻辑+低代码编排流程的最佳实践", keyword: "混合架构" },
    { text: "平台选型：按团队能力、迭代速度、定制需求三维度决策", keyword: "平台选型" }
  ],
  // 13.4 ReACT协议
  "adv-13-04-react": [
    { text: "ReACT三要素：思考推理意图、行动调用工具、观察获取反馈", keyword: "思考" },
    { text: "ReACT核心：思考(Thought)→行动(Action)→观察(Observation)循环", keyword: "核心思想" },
    { text: "vs CoT：ReACT多了行动和观察，能与外部环境交互", keyword: "Chain-of-Thought的对比" },
    { text: "Reflexion：执行后反思改进，自我纠错能力的增强", keyword: "Reflexion" }
  ],
  // 13.5 记忆、检索与上下文
  "adv-13-05-memory-retrieval": [
    { text: "Agent三级记忆：工作记忆(当前对话)/情景记忆/语义记忆", keyword: "工作记忆" },
    { text: "记忆检索：embedding相似度匹配，多级记忆分层召回", keyword: "情景记忆" },
    { text: "上下文管理：滑动窗口/摘要压缩/重要性排序三种策略", keyword: "滑动窗口" },
    { text: "RAG架构：query→检索→排序→注入context→生成", keyword: "基础RAG架构" }
  ],
  // 13.10 RAG技术
  "adv-13-10-rag": [
    { text: "RAG三件套：Embedding模型+向量数据库+Reranker", keyword: "RAG概述" },
    { text: "向量数据库：存储文档embedding，支持ANN近似最近邻检索", keyword: "向量数据库" },
    { text: "Reranker：粗检索后精排序，显著提升召回准确率", keyword: "Reranker模型" },
    { text: "多路召回：关键词+向量+知识图谱多种方式并行检索", keyword: "多路召回" },
    { text: "知识库构建：文档分块→embedding→索引的工程化流程", keyword: "知识库构建" }
  ]
};
